# Configurables for the MT->MX FTP listener
[mtMxListener]
name = "MT MX Listener 1"
# Protocol can be "ftp" or "sftp"
protocol = "ftp"
host = "127.0.0.1"
port = 23
username = "pan"
password = "pan"
# Path to the private key file for SFTP, if using SFTP
pvtKeyPath = ""
# Password for the private key, if applicable
keyPass = ""
pollingInterval = 1.0
# Directory where incoming MT files are placed
inwardFilepath = "/mt/inward/"
# Pattern to match incoming file names
inwardFileNamePattern = "(.*).txt"

# Uncomment the following section if you want to change the MT MX Client configuration
# Configurables for the MT->MX FTP client (used to send files)
# [mtMxClient]
# name = "MT MX Client 1"
# protocol = "ftp"
# host = "127.0.0.1"
# port = 23
# username = "pan"
# password = "pan"
# pvtKeyPath = ""
# keyPass = ""
# Directory where original MT messages are moved after successful processing
# successFilepath = "/mt/success/"
# Directory where original MT messages are moved after failed processing
# failedFilepath = "/mt/failed/"
# Directory where original MT messages are moved if processing skipped
# skippedFilepath = "/mt/skipped/"
# Directory where translated MT files are moved
# outwardFilepath = "/mt/outward/"

# Configurables for the MX->MT FTP listener
[mxMtListener]
name = "MX MT Listener 1"
# Protocol can be "ftp" or "sftp"
protocol = "ftp"
host = "127.0.0.1"
port = 23
username = "pan"
password = "pan"
# Path to the private key file for SFTP, if using SFTP
pvtKeyPath = ""
# Password for the private key, if applicable
keyPass = ""
pollingInterval = 1.0
# Directory where incoming MX files are placed
inwardFilepath = "/mx/inward/"
# Pattern to match incoming file names
inwardFileNamePattern = "(.*).txt"


# Uncomment the following section if you want to change the MX MT Client configuration
# Configurables for the MX->MT FTP client (used to send files)
# [mxMtClient]
# name = "MX MT Client 1"
# Protocol can be "ftp" or "sftp"
# protocol = "ftp"
# host = "127.0.0.1"
# port = 23
# username = "pan"
# password = "pan"
# pvtKeyPath = ""
# keyPass = ""
# Directory where original MX messages are moved after successful processing
# successFilepath = "/mx/success/"
# Directory where original MX messages are moved after failed processing
# failedFilepath = "/mx/failed/"
# Directory where original MX messages are moved if processing skipped
# skippedFilepath = "/mx/skipped/"
# Directory where translated MX files are moved
# outwardFilepath = "/test/abc/"


[ballerina.log]
level = "DEBUG"
format="json"

[log]
# Path to the dashboard log file
dashboardLogFilePath = "/swiftTranslator/logs/"
# Path to the Ballerina log file
ballerinaLogFilePath = "/swiftTranslator/logs/"


[translator]
supportedMTMessageTypes = [
    "103", "110", "111", "112", "190", "191", "192", "196", "199", "202", "205", "210", "290", "291", "292", "296",
    "299", "900", "910", "940", "942"
]
[translator.mxMtExtension]
preProcess = true
postProcess = true
basepath = "http://localhost:9090"

[translator.mtMxExtension]
preProcess = true
postProcess = true
basepath = "http://localhost:9090"

